"use client";
/* eslint-disable react/no-unescaped-entities, react/jsx-no-comment-textnodes */
import { useState } from "react";
import { ArrowUpRight, AudioLines, Braces, Check, ChevronDown, CirclePlay, Clapperboard, Gamepad2, Languages, Menu, Radio, Sparkles, Users, WandSparkles, X, Zap } from "lucide-react";

const tools = [
  {id:"01",icon:Languages,title:"Auto Video Translator",text:"Translate speech, captions, and on-screen context into 40+ languages while preserving timing and tone.",tags:["Speech-to-text","Subtitles","40+ languages"],color:"lime"},
  {id:"02",icon:AudioLines,title:"AI Voice Dubbing",text:"Create natural, lip-aware voiceovers with speaker detection, emotion control, and studio-grade cleanup.",tags:["Voice cloning","Lip sync","Multi-speaker"],color:"coral"},
  {id:"03",icon:Gamepad2,title:"Live Game Engine",text:"Turn gifts, comments, likes, and follows into real-time game actions your audience can play together.",tags:["Web games","Live events","OBS ready"],color:"blue"},
  {id:"04",icon:Braces,title:"TikTok Live API",text:"A developer-first event layer for building overlays, alerts, leaderboards, and interactive stream logic.",tags:["WebSocket","Webhooks","TypeScript SDK"],color:"violet"},
];
const faq = [
  ["Does thaomoc connect directly to TikTok Live?","The integration layer is designed around TikTok Live events. A production connection requires an eligible TikTok account and approved credentials; the experience shown here is a product preview."],
  ["Can the games run inside OBS?","Yes. Each game is delivered as a browser source with a transparent background, configurable event mapping, and a control panel for the host."],
  ["Do I need to code?","No for the creator tools. Developers can use the TypeScript SDK and event APIs for deeper customization."],
  ["Can I use my own AI voice?","Yes, with explicit voice-owner consent. You can also choose from licensed studio voices and configure language, pace, and emotion."],
];

export default function Home(){
 const [menu,setMenu]=useState(false),[open,setOpen]=useState<number|null>(0),[connected,setConnected]=useState(false),[events,setEvents]=useState(2847);
 const demo=()=>{setEvents(v=>v+1);setConnected(true)};
 return <main>
  <header className="site-header"><a className="brand" href="#top"><span className="brand-mark"><i/></span>thaomoc</a><nav className={menu?"nav-links open":"nav-links"}>{["Products","Developers","How it works","About"].map((x,i)=><a key={x} href={["#products","#developers","#how-it-works","#about"][i]} onClick={()=>setMenu(false)}>{x}</a>)}</nav><a className="header-cta" href="#contact">Build with us <ArrowUpRight size={16}/></a><button className="menu-button" onClick={()=>setMenu(!menu)} aria-label="Toggle menu">{menu?<X/>:<Menu/>}</button></header>
  <section className="hero" id="top"><div className="hero-grid"/><div className="hero-copy"><div className="eyebrow"><span/> CREATIVE TECHNOLOGY STUDIO</div><h1>Tools that make<br/><em>live content</em> feel alive.</h1><p>thaomoc builds AI-powered video tools, interactive livestream games, and developer APIs for the next generation of creators.</p><div className="hero-actions"><a className="button primary" href="#products">Explore our tools <ArrowUpRight size={18}/></a><a className="text-link" href="#developers"><CirclePlay size={19}/> See how it works</a></div><div className="hero-proof"><div><strong>40+</strong><span>Languages</span></div><div><strong>50ms</strong><span>Event latency</span></div><div><strong>24/7</strong><span>Creator uptime</span></div></div></div>
   <div className="studio-shell"><div className="studio-topbar"><div className="studio-brand"><span className="mini-mark"/> thaomoc studio</div><div className="window-dots"><i/><i/><i/></div><div className="live-badge"><span/> LIVE</div></div><div className="studio-body"><aside className="studio-rail">{[Clapperboard,AudioLines,Gamepad2,Braces].map((I,i)=><button className={i===0?"active":""} key={i}><I size={18}/></button>)}</aside><div className="game-preview"><div className="game-meta"><span>LIVE GAME</span><span><Users size={13}/> 1,248</span></div><div className="arena"><div className="orb a">A</div><div className="orb b">B</div><div className="orb c">C</div><div className="orb d">D</div><div className="arena-core"><Zap size={27}/><b>COMBO</b><strong>x12</strong></div></div><div className="score-row"><span>TOP SQUAD</span><b>84,920</b><span>02:18 LEFT</span></div></div><div className="event-feed"><div className="feed-title"><span>Live events</span><span className="status-dot"/></div>{[["M","minnie.dev","sent a Rose","+1"],["J","joshplays","joined","NEW"],["K","kira.exe","sent a Galaxy","+1000"],["A","alex.studio","liked × 24","+24"]].map((r,i)=><div className="feed-item" key={r[1]}><span className={`avatar a${i}`}>{r[0]}</span><p><b>{r[1]}</b><small>{r[2]}</small></p><em>{r[3]}</em></div>)}<button onClick={demo} className="simulate"><Sparkles size={14}/> Simulate event</button></div></div><div className="floating-toast"><span>+1</span><p><b>Rose received!</b><small>Game action triggered</small></p></div></div>
  </section>
  <section className="ticker"><div>AI VIDEO <span>✦</span> LIVE GAMES <span>✦</span> TIKTOK API <span>✦</span> VOICE DUBBING <span>✦</span> REAL-TIME EXPERIENCES <span>✦</span> AI VIDEO <span>✦</span> LIVE GAMES <span>✦</span> TIKTOK API <span>✦</span> VOICE DUBBING <span>✦</span></div></section>
  <section className="products section" id="products"><div className="section-heading"><div><span className="section-number">01</span><span className="kicker">WHAT WE BUILD</span></div><h2>One studio.<br/>Four powerful tools.</h2><p>Everything creators and developers need to make global, interactive, and unforgettable live content.</p></div><div className="tool-grid">{tools.map(t=>{const Icon=t.icon;return <article className={`tool-card ${t.color}`} key={t.id}><div className="card-head"><span className="tool-icon"><Icon/></span><span>{t.id}</span></div><h3>{t.title}</h3><p>{t.text}</p><div className="tag-row">{t.tags.map(x=><span key={x}>{x}</span>)}</div><a href="#contact">Learn more <ArrowUpRight size={17}/></a></article>})}</div></section>
  <section className="workflow section" id="how-it-works"><div className="workflow-copy"><span className="section-number light">02</span><span className="kicker light">FROM SIGNAL TO PLAY</span><h2>Your audience does something.<br/><em>Your experience reacts.</em></h2><p>We turn live platform signals into safe, instant game actions. No scene switching. No manual triggers. Just a stream that responds.</p><div className="steps">{[["Connect your live","Authorize an eligible creator account."],["Choose an experience","Launch a game, overlay, or custom event flow."],["Go live and play","Audience events become gameplay in real time."]].map((s,i)=><div key={s[0]}><b>{i+1}</b><p><strong>{s[0]}</strong><span>{s[1]}</span></p></div>)}</div></div><div className="signal-board"><div className="board-header"><span>EVENT ROUTER</span><span className={connected?"connection active":"connection"}>{connected?"Demo connected":"Preview mode"}</span></div><div className="signal-flow"><div className="signal-source"><span className="tiktok-note">♪</span><b>TikTok LIVE</b><small>Event source</small></div><div className="pulse-line"><span/></div><div className="signal-engine"><Zap/><b>thaomoc</b><small>Rules engine</small></div><div className="pulse-line second"><span/></div><div className="signal-source"><Gamepad2/><b>Web Game</b><small>Browser source</small></div></div><div className="event-log"><div className="log-head"><span>REAL-TIME LOG</span><b>{events} events</b></div><code><i>12:41:08</i> gift.received <b>{'{ gift: "Rose", count: 1 }'}</b></code><code><i>12:41:08</i> rule.matched <b>{'{ action: "boost_player" }'}</b></code><code><i>12:41:08</i> game.updated <b>{'{ score: "+100" }'}</b></code></div><button className="event-button" onClick={demo}><Radio size={16}/> Send demo event</button></div></section>
  <section className="developer section" id="developers"><div className="dev-copy"><span className="section-number">03</span><span className="kicker">BUILT FOR DEVELOPERS, TOO</span><h2>Ship live experiences<br/>without rebuilding the plumbing.</h2><p>A typed event API, flexible webhooks, and browser-safe SDKs give your team a clean foundation for custom livestream products.</p><ul>{["Typed TypeScript SDK","Event replay & idempotency","Local sandbox and test events","WebSocket + webhook delivery"].map(x=><li key={x}><Check/>{x}</li>)}</ul><a className="button dark" href="#contact">Read the API overview <ArrowUpRight size={18}/></a></div><div className="code-window"><div className="code-tabs"><span className="active">quickstart.ts</span><span>events.json</span><i>SDK v1.4</i></div><pre><code><span className="pink">import</span> {'{ ThaomocLive }'} <span className="pink">from</span> <span className="green">'@thaomoc/live'</span>;
{"\n\n"}<span className="pink">const</span> live = <span className="pink">new</span> <span className="blue">ThaomocLive</span>({'{'}
{"\n"}  channel: <span className="green">'@yourchannel'</span>,
{"\n"}  mode: <span className="green">'sandbox'</span>
{"\n"}{'}'});
{"\n\n"}live.<span className="blue">on</span>(<span className="green">'gift.received'</span>, <span className="pink">async</span> (event) =&gt; {'{'}
{"\n"}  <span className="muted">// Map gifts to game logic</span>
{"\n"}  <span className="pink">await</span> game.<span className="blue">trigger</span>({'{'} action: <span className="green">'spawn_powerup'</span> {'}'});
{"\n"}{'}'});</code></pre><div className="code-status"><span><i/> Listening for live events</span><b>50ms avg.</b></div></div></section>
  <section className="manifesto section" id="about"><div className="manifesto-mark"><WandSparkles/></div><p>We believe live content should be more than something people watch.</p><h2>It should listen back.</h2><div className="manifesto-bottom"><span>DESIGNED IN VIETNAM · BUILT FOR EVERYWHERE</span><span>THAOMOC / 2026</span></div></section>
  <section className="faq section"><div className="faq-title"><span className="section-number">04</span><span className="kicker">QUESTIONS, ANSWERED</span><h2>The details<br/>behind the magic.</h2></div><div className="faq-list">{faq.map(([q,a],i)=><div className="faq-item" key={q}><button onClick={()=>setOpen(open===i?null:i)}><span>{q}</span><ChevronDown className={open===i?"rotated":""}/></button>{open===i&&<p>{a}</p>}</div>)}</div></section>
  <section className="final-cta" id="contact"><div className="cta-orbit"><i/><i/><i/></div><span>HAVE AN IDEA?</span><h2>Let’s make your<br/>livestream <em>playable.</em></h2><a className="button primary big" href="mailto:hello@thaomoc.dev">Start a project <ArrowUpRight/></a></section>
  <footer><a className="brand footer-brand" href="#top"><span className="brand-mark"><i/></span>thaomoc</a><p>Creative technology for the live generation.</p><div><a href="#products">Products</a><a href="#developers">Developers</a><a href="mailto:hello@thaomoc.dev">Contact</a></div><small>© 2026 thaomoc studio.</small></footer>
 </main>
}
